server:
  port: 9999
  servlet:
    context-path: /demo1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zk199624
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.edu.springbootproject.entity
